# Site settings
short_title: École des Données 
url: "http://ecoledesdonnees.org" # the base hostname & protocol for your site
github_repo: ecoledesdonnees

devs:
  -
      name: Sam Smith
      github: mintcanary

contributors:
  -
      name: Pierre Chrzanowski 
      link: https://ecoledesdonnees.github.io/site/
  -
      name: Cécile Le Guen
      link: https://ecoledesdonnees.github.io/site/
  -
      name: Samuel Goëta
      link: https://ecoledesdonnees.github.io/site/
  -
      name: Sylvia Fredriksson
      link: https://ecoledesdonnees.github.io/site/
      
#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

meta:
  resources:
    label: resources
    output: true
    has_translation: false
    title: Cours
    filters:
      - Topic
      - Language
      - Region
      - MediaType

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts


related_projects:
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/

