# Site settings
short_title: École des Données 
url: "http://ecoledesdonnees.org" # the base hostname & protocol for your site
github_repo: ecoledesdonnees

devs:
  -
      name: Sam Smith
      github: mintcanary

contributors:
  -
      name: Rufus Pollock
      link: http://rufuspollock.org/
#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts


related_projects:
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/

